server.port: 8085

spring:
  application:
    name: reservation-service

  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


